### ISSUE TITLE
Unexpected keyword argument 'nonposy' while running MEASURE_LINEAR_VIBRATIONS_RANGE

### ISSUE THREAD

**Issue by samuellazea** [worksasintended/klipper_linear_movement_analysis#10]
Testing some vibrations but it seems there is some issue with it
Internal error on command:"MEASURE_LINEAR_VIBRATIONS_RANGE"

`output written to /home/pi/klipper_config/linear_vibrations/relative_power2022-11-09T00:22:52.056255.png
output written to /home/pi/klipper_config/linear_vibrations/peak_frequencies2022-11-09T00:22:52.521933.png
Internal error on command:"MEASURE_LINEAR_VIBRATIONS_RANGE"
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 135, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/linear_movement_vibrations.py", line 157, in cmd_MEASURE_LINEAR_VIBRATIONS_RANGE
    step_distance=step_distance, rotation_distance=rotation_dist, f_max=f_max)
  File "/home/pi/klipper/klippy/extras/linear_movement_vibrations.py", line 405, in _plot_peak_frequencies
    ax.set_xscale('log', nonposx='clip')
  File "/home/pi/klippy-env/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 4117, in set_yscale
    ax.yaxis._set_scale(value, **kwargs)
  File "/home/pi/klippy-env/lib/python3.7/site-packages/matplotlib/axis.py", line 761, in _set_scale
    self._scale = mscale.scale_factory(value, self, **kwargs)
  File "/home/pi/klippy-env/lib/python3.7/site-packages/matplotlib/scale.py", line 597, in scale_factory
    return scale_cls(axis, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'nonposy'
Transition to shutdown state: Internal error on command:"MEASURE_LINEAR_VIBRATIONS_RANGE"
Dumping gcode input 0 blocks
Dumping 20 requests for client 2955437552`

He is generating some graphs but then suddenly die after reaching 300ms and saving the output
Added the log for more info

[klippy(1).log](https://github.com/worksasintended/klipper_linear_movement_analysis/files/9966290/klippy.1.log)
![Screenshot_20221109_020232](https://user-images.githubusercontent.com/6168211/200708167-90b074aa-1cb0-404c-bfc5-686f501d9b3f.jpeg)
![Screenshot_20221109_020217](https://user-images.githubusercontent.com/6168211/200708173-6764e477-9d98-47aa-b0cd-f059dff47811.jpeg)
![Screenshot_20221109_020142](https://user-images.githubusercontent.com/6168211/200708175-26adb4b1-27ec-4e58-8430-0be84a3fc8fa.jpeg)

**Comment by worksasintended** [comment]
Thanks for bringing up. This was due a version incompatibility and has been fixed.
